require("plugins-setup")
require("core.options")
require("core.keymaps")
require("core.colorscheme")
require("plugins.nvim-tree")
require("plugins.comment")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.nvim-cmp")
require("plugins.autopairs")
require("plugins.gitsigns")
require("plugins.treesitter")
require("plugins.autosave")
require("plugins.lsp.mason")
require("plugins.lsp.lspconfig")
require("plugins.lsp.lspsaga")
require("plugins.lsp.null-ls")


